CORRECTION OF CODE - ERROR ON LINE 198
 Line 198 was changed because it sent the following error:
     " b = self.norm.inverse(self._uniform_y(self.cmap.N +1))
      AttributeError: 'str' object has no attribute 'N' "
Caused by sending a string and not the cmap object, the solution is on line 200, which sends the corresponding cmap object to the cmap value.